for i=1:max(size(include))
        if Ldonut_mask_corr(rowD(include(i))-1,colD(include(i))-1)==1 &&...
                Ldonut_mask_corr(rowD(include(i))-1,colD(include(i)))==1 && ...
                Ldonut_mask_corr(rowD(include(i))-1,colD(include(i))+1)==1 &&...
                Ldonut_mask_corr(rowD(include(i)),colD(include(i))-1)==1 &&...
                Ldonut_mask_corr(rowD(include(i)),colD(include(i))+1)==1 &&...
                Ldonut_mask_corr(rowD(include(i))+1,colD(include(i))-1)==1 &&...
                Ldonut_mask_corr(rowD(include(i))+1,colD(include(i)))==1 && ...
                Ldonut_mask_corr(rowD(include(i))+1,colD(include(i))+1)==1
            Ldonut_mask_corr_outl(rowD(include(i)),colD(include(i)))=0;
        else
            Ldonut_mask_corr_outl(rowD(include(i)),colD(include(i)))=1;
        end
end